[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/riscv32imc-unknown-none-elf/debug/wokwi-interaction"
firmware = "target/riscv32imc-unknown-none-elf/debug/wokwi-interaction"

# link: https://wokwi.com/projects/449397144770966529